runtime: python311

env: standard
auto_scaling:
  min_instances: 1
  max_instances: 5

env_variables:
  ENVIRONMENT: production
  DEBUG: "false"

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
